@AuthService_HostAddress = http://localhost:5012

POST {{AuthService_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john1@test.com",
  "password": "Password1"
}
###

POST {{AuthService_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "john1@test.com",
  "password": "Password1"
}